### ISSUE TITLE
undefined identifier loadGLFW, when using BindGLFW_Static

### ISSUE THREAD

**Issue by HuskyNator** [BindBC/bindbc-glfw#12]
When I use the 'BindGLFW_Static' version directive, I get the build error; `Error: undefined identifier loadGLFW`, when trying to use `loadGLFW`. This does not happen when not using the directive, with everything functioning seemingly normal.
The library files I have present are 'glfw3.dll', 'glfw3.lib' & 'glfw3dll.lib', with my dub.json looking like this:
```
{
	"authors": [
		"HuskyNator"
	],
	"copyright": "Copyright © 2021, HuskyNator",
	"dependencies": {
		"bindbc-glfw": "~>0.10.1",
		"bindbc-opengl": "~>0.13.0"
	},
	"description": "Learning OpenGL (in Dutch)",
	"libs": ["glfw3"],
	"license": "proprietary",
	"name": "hoekjed",
	"versions": [ "BindGLFW_Static", "GLFW_33", "GL_46"]
}
```
I have tried using both 'glfw3 and 'glfw3dll' within the libs property, and also tried this without the GLFW_33 directive.

**Comment by mdparker** [comment]
That's because when using the static binding, the `loadGLFW` function is not compiled as there is no need to load the DLL manually. The system loader will do it for you. Just link with `glfw3dll.lib`, remove the call to `loadGLFW`, and put the DLL in the exexutable's directory.

**Comment by HuskyNator** [comment]
Oh I see, thanks!
If it's ok, I'd like to ask you if you also know how to make to make a standalone executable, instead of requiring the DLL, I seem to be understanding the whole concept of static linking wrong, but cant find much regarding it for dub. 😅

**Comment by mdparker** [comment]
In that case, you link with `glfw3.lib`, which is the static library, instead of `glfw3dll.lib`, which is the import library for the DLL. But when static linking, you also need to link with all of GLFW's dependencies, like `OpenGL32.lib`, `gdi32.lib`, `kernel32.lib`, and `user32.lib`, IIRC. And there may be more. That's just on Windows. On Linux, it will be different. And again on Mac.

IMO, it's much better just to make use of the DLL. Then you don't have to worry about the dependencies, and you can update GLFW without recompiling the app. I haven't bothered with static libraries in ages.

**Comment by HuskyNator** [comment]
Ouch that sounds a lot more complex, also, doesn't me linking to glfw3dll.lib mean I'm already tied to one platform, or would I just have to add a different dll file?
Also, sorry for the load of questions, should bindbc-glfw (or bindbc-opengl for that matter) provide documentation? (In which case, should I be using the include folder from glfw somewhere/how?)

**Comment by mdparker** [comment]
> Ouch that sounds a lot more complex

It just means adding the proper libraries to your configuration. Do it once and you're done. But static binding also means that any time you want to update to a new version of a library, you have to recompile and relink the program with the new library versions even if there are no updates to the program itself. With shared libraries, you just replace the old ones with the new ones and everything will be fine most of the time (as long as the library developers properly maintain the interface).

> doesn't me linking to glfw3dll.lib mean I'm already tied to one platform

Your binaries, including the executable, are already tied to one platform. DLLs are Windows-only. Other platforms use "shared objects" (`.so`) or "dynamic libraries" (`.dylib`). If you want to distribute on other platforms you'll need to recompile anyway and link to platform-specific libraries. For example, on Linux, you would link with `glfw3.so` or, for static linking, the Linux version of `glfw3.lib`. That's why I like dynamic bindings, because there's no link-time dependencies at all. You just build your program for each platform without worrying about linking anything, then load the shared libraries at runtime.

>should bindbc-glfw (or bindbc-opengl for that matter) provide documentation

Everything you need to know to use the BindBC packages is in the README file of each repository. They're bindings. There's very little to document beyond how to configure them, compile them, and how to load the shared libraries dynamically. Information about linkers, loaders, static libraries, shared libraries, etc., and how they all work, is quite beyond the scope.

That said, I did write up something for Derelict (the ancestor of BindBC) a while back [that explains some of the terminology](http://derelictorg.github.io/bindings/). And later this month or early next month I'll be announcing a tutorial that talks about linking, loading, objects, libraries, and so on. It's aimed at people who have no prior background in statically compiled languages like C and C++. Most everything written about D assumes basic knowledge about the tooling, because there was a time when the majority of programmers could be expected to have that background. That's no longer true. So that should help clear up the fog in situations like this.

**Comment by HuskyNator** [comment]
I'm sorry, I may have been unclear about that documentation part.
What I meant was that, in contrast to when I used Cmake before, in which case I was able to get autocomplete documentation using the include folder provided in the GLFW precompiled binaries zip, I'm unaware of a way of achieving the same thing using dlang or this library, which doesn't seem to contain the documention on functions/classes/etc by itself.

**Comment by mdparker** [comment]
I see. D supports inline documentation [in the form of Ddoc](https://dlang.org/spec/ddoc.html). I don't include it with my bindings because the documentation already exists for the C libraries. I understand some people like to have it in a popup in their IDE, but I maintain the bindings by hand and I'm just not going to do expend needless effort on repeating documentation that already exists.
