### ISSUE TITLE
Height always 0 for glfwSetFramebufferSizeCallback callback

### ISSUE THREAD

**Issue by RUSshy** [BindBC/bindbc-glfw#3]
Hi

When i setup a callback for: ``glfwSetFramebufferSizeCallback``

I get wrong value when i resize the window, it's always 0 for height, wich is wrong:

```
EVENT: onResize(777, 0)
EVENT: onResize(781, 0)
EVENT: onResize(782, 0)
EVENT: onResize(784, 0)
EVENT: onResize(784, 0)
EVENT: onResize(786, 0)
```

Example:
```D
import std.stdio;
import std.conv;
import std.string;

import bindbc.opengl;
import bindbc.glfw;

const GLuint WIDTH = 1280, HEIGHT = 720;

abstract class Engine
{
	private GLFWwindow* _window;
	private int _width = 1280;
	private int _height = 720;
	private int _backbufferWidth;
	private int _backbufferHeight;
	private int _logicalWidth;
	private int _logicalHeight;

	extern (C) void onFrameBufferResize(GLFWwindow* window, int width, int height)
	{
		writeln(format("EVENT: onResize(%s, %s)", width, height));
		glViewport(0, 0, width, height);
		// updateBackbufferInfo();		
	}

	private void updateBackbufferInfo()
	{
		glfwGetFramebufferSize(_window, &_backbufferWidth, &_backbufferHeight);
		glfwGetWindowSize(_window, &_logicalWidth, &_logicalHeight);
	}

	public void run()
	{
		GLFWSupport ret = loadGLFW();

		if (ret != glfwSupport)
		{

			// Handle error. For most use cases, its reasonable to use the the error handling API in
			// bindbc-loader to retrieve error messages for logging and then abort. If necessary, it's 
			// possible to determine the root cause via the return value:

			if (ret == GLFWSupport.noLibrary)
			{

				writeln("ERROR: unable to find glfw3 library");
			}
			else if (GLFWSupport.badLibrary)
			{
				// One or more symbols failed to load. The likely cause is that the
				// shared library is for a lower version than bindbc-glfw was configured
				// to load (via GLFW_31, GLFW_32 etc.)
				writeln("ERROR: wrong library shit");
			}
		}

		if (!glfwInit())
			return;

		glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
		glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
		glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
		glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);

		_window = glfwCreateWindow(_width, _height, "Hi D", null, null);
		if (!_window)
		{
			glfwTerminate();
			return;
		}

		glfwMakeContextCurrent(_window);
		glfwSwapInterval(1);

		GLSupport retVal = loadOpenGL();
		if (retVal == GLSupport.gl41)
		{
			// configure renderer for OpenGL 4.1
			writeln("Hi gl4.1");
		}
		else if (retVal == GLSupport.gl33)
		{
			// configure renderer for OpenGL 3.3
			writeln("hi gl3.3");
		}
		else
		{
			// Error
			writeln("yo err");
		}

		writefln("Vendor:   %s", to!string(glGetString(GL_VENDOR)));
		writefln("Renderer: %s", to!string(glGetString(GL_RENDERER)));
		writefln("Version:  %s", to!string(glGetString(GL_VERSION)));
		writefln("GLSL:     %s", to!string(glGetString(GL_SHADING_LANGUAGE_VERSION)));

		glViewport(0, 0, WIDTH, HEIGHT);

		glfwSetFramebufferSizeCallback(_window, cast(GLFWframebuffersizefun)&onFrameBufferResize);

		while (!glfwWindowShouldClose(_window))
		{
			glfwPollEvents();

			glClearColor(0.2f, 0.2f, 0.2f, 1.0f);
			glClear(GL_COLOR_BUFFER_BIT);

			// stuff

			glfwSwapBuffers(_window);
		}

		glfwTerminate();
	}

}

int main()
{
	auto myGame = new MyGame;
	myGame.run();

	return 0;
}

class MyGame : Engine
{
}

```

**Comment by RUSshy** [comment]
![znra46pxvp](https://user-images.githubusercontent.com/18348637/53670635-b5c8f200-3c7b-11e9-94d0-cf651d23c454.gif)

**Comment by mdparker** [comment]
The declarations in the binding look good. Please test out the same program in C and see what sort of results you get.

**Comment by RUSshy** [comment]
It works fine in one of my C++ project

Maybe it's the way i setup the callback ?

```D

extern (C) void onFrameBufferResize(GLFWwindow* window, int width, int height)
{	
}

glfwSetFramebufferSizeCallback(_window, cast(GLFWframebuffersizefun)&onFrameBufferResize);

```

Is it how it should be done ?

**Comment by RUSshy** [comment]
Without the cast i get this error btw:

``sandbox\source\main.d(87,33): Error: function pointer glfwSetFramebufferSizeCallback(GLFWwindow*, extern (C) void function(GLFWwindow*, int, int) nothrow) is not callable using argument types (GLFWwindow*, extern (C) void delegate(GLFWwindow* window, int width, int height))``

**Comment by mdparker** [comment]
Oh, I didn't pay enough attention to your code before. The error message is telling you exactly the problem. First, look at the first line:

`function pointer glfwSetFramebufferSizeCallback(GLFWwindow*, extern (C) void function(GLFWwindow*, int, int) nothrow)`

The functoin extpects a `GLFWwindow*` as the first parameter and the second parameter is expected to be a function pointer which is both `extern(C)` and  `nothrow`. That's because all callbacks in the binding are declared to be `extern(C) nothrow`, as you can see here:

https://github.com/BindBC/bindbc-glfw/blob/master/source/bindbc/glfw/types.d#L336

But that's secondary to the real problem, which is described in the next part of the error message:

`is not callable using argument types (GLFWwindow*, extern (C) void delegate(GLFWwindow* window, int width, int height))`

This is showing the actual arguments you passed the function: `GLFWwindow*` and a delegate. A delegate *is not a function pointer*.

 `onFrameBufferResize` is a member function in your `Engine` class. This means that when you take a pointer to it, you're getting a delegate, not a function pointer. You'll either need to make it `static` or move it outside the class declaration. See:

https://dlang.org/spec/function.html#closures

And don't forget to declare the callback function as `nothrow`.

**Comment by RUSshy** [comment]
Ohh i see now !! thanks for the detailed explanation

So there is no way to setup a non static callback inside the Engine class ? the ``cast()`` trick seemed to be good, expect for the ``height always 0`` issue

And with the nothrow, i remember having many other issues with it, like format() not working anymore, or all my other functions needed to be nothrow too, that's a bit annoying

I'm new to D, there is still load of things i have to learn properly

**Comment by mdparker** [comment]
> So there is no way to setup a non static callback inside the Engine class ?

No.

> the cast() trick seemed to be good, except for the height always 0 issue

A delegate is a pair of pointers, whereas a function pointer is just one. So you were passing two pointers where the function is expecting one. The cast forced the compiler to interpret it as a single pointer. Any time you do something like that you're bound to end up with invalid data if not an outright crash.

> And with the nothrow, i remember having many other issues with it, like format() not working anymore, or all my other functions needed to be nothrow too, that's a bit annoying

The callbacks need to be `nothrow` because they're called from the C side. There's no guarantee that an exception thrown from the D side will correctly propagate up the callstack through the C side and back to D again.

You can wrap functions like `format` and `writefln` in a try catch block and handle the exception before returning from the callback, but you should also take subclasses of `Error` into account. I wrote an article a few years ago showing one approach to it. It's still applicable.

https://www.gamedev.net/articles/programming/general-and-gameplay-programming/d-exceptions-and-c-callbacks-r3323

Since this seems to have resolved your issue, I'm going to close it. Next time, please take things like this to the Learn forum and be sure it's an issue with the library and not your code before reporting an issue here.

Thanks!

**Comment by RUSshy** [comment]
Thanks a lot for these informations, really usefull!
